### ISSUE TITLE
Crash querying Google OnHub device: 'NoneType' object has no attribute 'findtext'

### ISSUE THREAD

**Issue by mhansen** [yrro/igd-exporter#1] opened 2019-11-30 05:10 UTC
Hi there, I just tried probing my network then running the probe: I see this in the logs, and a server error over HTTP.

::ffff:192.168.86.31 - - [30/Nov/2019 16:08:57] "GET /probe?target=http%3A%2F%2F192.168.86.1%3A5000%2FrootDesc.xml HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/pi/.local/lib/python3.7/site-packages/igd_exporter/exporter.py", line 20, in wsgi_app
    return probe(environ, start_response)
  File "/home/pi/.local/lib/python3.7/site-packages/igd_exporter/exporter.py", line 99, in probe
    reg.register(igd.probe(qs['target'][0]))
  File "/home/pi/.local/lib/python3.7/site-packages/igd_exporter/igd.py", line 151, in probe
    device = probe_device(target_url)
  File "/home/pi/.local/lib/python3.7/site-packages/igd_exporter/igd.py", line 182, in probe_device
    url_path = device.findtext("d:serviceList/d:service[d:serviceType='urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1']/d:controlURL", namespaces=ns)
AttributeError: 'NoneType' object has no attribute 'findtext'

**Comment by mhansen** [comment] 2020-01-12 01:25
Looks like it's looking for a deviceType urn:schemas-upnp-org:device:InternetGatewayDevice:1
, when the onHub ends with `:2` instead of `:1`.

**Comment by yrro** [comment] 2022-06-17 12:44
Assuming this is a dupe of #4

**Closed as completed by yrro** 2022-06-17 12:44 UTC
